### ISSUE TITLE
Grafana plugin does not work anymore with latest Yamcs server

### ISSUE THREAD

**Issue by nmaas87** [yamcs/grafana-yamcs#11] opened 2022-07-13 04:55 UTC
Using the latest Yamcs server 5.7.4, the Yamcs Grafana plugin (latest 2.2.1 - used in Grafana 8.2.6) is not working anymore.
All graphs show "Resource not found".

![resourcenofound](https://user-images.githubusercontent.com/1331457/178653105-6803a62c-20b6-495a-bd5c-1b108cba6e25.png)

I have not had the need to use Grafana for some time, so it could also have happend already on 5.7.x transistion, latest configuration I noted was working is Plugin 2.2.1 wih Grafana 8.2.6 and Yamcs server 5.5.3

Could you please fix the issue?

**Comment by fgretief** [comment] 2022-08-03 11:16
I came across this same issue today with Yamcs v5.6.2 and the Grafana Plugin v2.2.1.  The Grafana query inspector gave the following result for a Parameter input of `/FakeSat/N30_P100_ext1`:
```json
{  
	"request": {    
		"method": "GET",    
		"url": "api/datasources/proxy/1/api/archive/fakesat/parameters%2FFakeSat%2FN30_P100_ext1/samples",    
		"params": {      
			"start": "2022-08-03T04:49:08.722Z",
			"stop": "2022-08-03T10:49:08.722Z",
			"useRawValue": true,
			"count": 1488
		},
		"hideFromInspector": false
	},  
	"response": {    
		"message": "Resource not found\r\n",    
		"error": "Not Found",    
		"response": "Resource not found\r\n"  
	}
}
```

The issue seems to be the first `%2F` in that URL. The Yamcs server seems to be unable to process that string. If one replace the `%2F` with a `/` character, then the URL work via a browser.

From the Yamcs server logs the following is a failure:
```
Aug 03 13:05:16.251 _global [3213] org.yamcs.http.HttpRequestHandler [FINE] c768806b GET /api/archive/fakesat/parameters%2FFakeSat%2FN30_P100_ext1/samples
Aug 03 13:05:16.252 _global [3213] org.yamcs.http.HttpRequestHandler [WARNING] /api/archive/fakesat/parameters%2FFakeSat%2FN30_P100_ext1/samples: Resource not found
Aug 03 13:05:16.252 _global [3213] org.yamcs.http.HttpRequestHandler [WARNING] c768806b GET /api/archive/fakesat/parameters%2FFakeSat%2FN30_P100_ext1/samples 404
```

While this is a success:
```
Aug 03 13:05:23.820 _global [191] org.yamcs.http.HttpRequestHandler [FINE] d5f937f5 GET /api/archive/fakesat/parameters/FakeSat%2FN30_P100_ext1/samples
Aug 03 13:05:23.820 _global [191] org.yamcs.http.HttpRequestHandler [FINE] 1138: Routing GET /api/archive/fakesat/parameters/FakeSat%2FN30_P100_ext1/samples
Aug 03 13:05:23.843 _global [191] org.yamcs.http.HttpRequestHandler [INFO] d5f937f5 GET /api/archive/fakesat/parameters/FakeSat%2FN30_P100_ext1/samples 200
Aug 03 13:05:23.843 _global [191] org.yamcs.http.Context[c1138] [FINE] API call finished successfully, transferred bytes: 0
```

So to solve the issue, either the plugin needs to ensure that the first `%2F` becomes a `/` character, or the Yamcs server should be fixed to handle the `%2F` properly.

**Comment by fqqb** [comment] 2022-08-03 13:34
Thanks, that works.

I was able to reproduce on Grafana 8 as well, so I think it's Yamcs that became more strict when dealing with `%2F` (not a valid path seperator), which I'd say is a good thing.

FYI, also accepted would be something like this where there is no `%2F` at all: `/api/archive/fakesat/parameters/FakeSat/N30_P100_ext1/samples`

Published a release for this:
https://github.com/yamcs/grafana-yamcs/releases/tag/v2.2.2

**Closed as completed by fqqb** 2022-08-03 13:34 UTC
